version: '2'
services:
  a:
    image: tutum/hello-world
    container_name: foo
    networks:
      front:
        aliases:
          - web
  b:
    image: tutum/hello-world
    networks:
      back:
        aliases:
          - website
      front:
        aliases:
          - web
  c:
    image: tutum/hello-world
    networks:
      - back
networks:
  front:
    driver: bridge
  back:
    driver: bridge
