version: '2'
services:
  worker:
    image: tutum/hello-world
    command: sh -c "while true; do echo ke; done"
    logging:
      driver: syslog
      options:
        syslog-address: "logs4.papertrailapp.com:30696"
